all: minesweeper.o ; gcc minesweeper.o -o mine

minesweeper.o: minesweeper.c macros_variables_and_declarations.h ; gcc minesweeper.c -c -o minesweeper.o

# normaalgezien kan je ook all: ... op de eerste lijn zetten en wat erachter volgt op lijnen eronder
# zetten met een tab voor de lijn, maar aangezien mijn IDE tabs automatisch naar spaties omzet en de
# setting om dit niet meer te doen het probleem niet oplost heb ik bovenstaande notatie gebruikt.
